In [5]:
import tensorflow as tf

In [7]:
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.7.0


## 1. Operations on constants

In [11]:
tensor_1 = tf.constant(3) # scalar
tensor_1

In [24]:
tf.print(tensor_1)

3


In [18]:
tensor_2 = tf.constant([1,2]) # array
tensor_2

In [22]:
tf.print(tensor_2)

[1 2]


In [20]:
tensor_3 = tf.constant([[1, 2], [3, 4]]) # matrix
tensor_3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [21]:
tf.print(tensor_3)

[[1 2]
 [3 4]]


In [25]:
print(tf.rank(tensor_3))

tf.Tensor(2, shape=(), dtype=int32)


In [26]:
tensor_3.numpy()

array([[1, 2],
       [3, 4]], dtype=int32)

### Addition

In [32]:
tensor_add = tf.add(tensor_2, tensor_2)

In [33]:
tf.print(tensor_add)

[2 4]


### Multiplication

In [30]:
tensor_multi = tf.matmul(tensor_3, tensor_3)

In [31]:
tf.print(tensor_multi)

[[7 10]
 [15 22]]


### Reduce

In [37]:
tensor_4 = tf.constant([[4.0, 5.0], [10.0, 1.0]], name='tf_reduce')

In [38]:
# Find the largest value
print(tf.reduce_max(tensor_4))

tf.Tensor(10.0, shape=(), dtype=float32)


In [39]:
# Find the index of the largest value
print(tf.argmax(tensor_4))

tf.Tensor([1 0], shape=(2,), dtype=int64)


### Gradient

In [40]:
x = tf.constant(2.0)

In [41]:
with tf.GradientTape(persistent=True) as g:
    g.watch(x)
    y = x * x
    z = y * y
    
dy_dx = g.gradient(y, x)
dz_dx = g.gradient(z, x)

In [42]:
print(dy_dx)

tf.Tensor(4.0, shape=(), dtype=float32)


In [43]:
print(dz_dx)

tf.Tensor(32.0, shape=(), dtype=float32)


## 2. Operations on variables

In [49]:
var_1 = tf.Variable([[1.0, 2.0], [3.0, 4.0]])

In [46]:
print("Viewed as a tensor:", tf.convert_to_tensor(var_1))

Viewed as a tensor: tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [47]:
# This creates a new tensor; it does not reshape the variable.
print("Copying and reshaping: ", tf.reshape(var_1, [1,4]))

Copying and reshaping:  tf.Tensor([[1. 2. 3. 4.]], shape=(1, 4), dtype=float32)


### Addition

In [55]:
var_add = tf.add(var_1, var_1)

In [56]:
tf.print(var_add)

[[2 4]
 [6 8]]


### Assign

In [52]:
var_2 = tf.Variable([1.0, 2.0])

In [53]:
# Create var_3 based on the value of var_2
var_3 = tf.Variable(var_2)
var_2.assign([3, 4])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([3., 4.], dtype=float32)>

In [54]:
# Other versions of assign
print(var_2.assign_add([2,3]).numpy())  # [5. 7.]
print(var_2.assign_sub([5,7]).numpy())  # [0. 0.]

[5. 7.]
[0. 0.]


## Operations on placeholders

In [58]:
x = tf.placeholder("float", None)
y = x * 2

with tf.Session() as session:
    result = session.run(y, feed_dict={x: [1, 2, 3]})
    print(result)

AttributeError: module 'tensorflow' has no attribute 'placeholder'

In [59]:
tf.placeholder()

AttributeError: module 'tensorflow' has no attribute 'placeholder'